<!--
 * @Author: your name
 * @Date: 2021-04-12 22:37:32
 * @LastEditTime: 2021-07-22 15:49:26
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /production_web/src/components/base/Loading.vue
-->
<template>
  <div class="loadingio-spinner-bean-eater-0lnlvb57159i"><div class="ldio-acn7vapfu5">
    <div><div /><div /><div /></div><div><div /><div /><div /></div>
  </div></div>

</template>

<script>
</script>

<style scoped lang="scss">
@keyframes ldio-acn7vapfu5-1 {

  0% { transform: rotate(0deg) }

  50% { transform: rotate(-45deg) }

  100% { transform: rotate(0deg) }
}
@keyframes ldio-acn7vapfu5-2 {

  0% { transform: rotate(180deg) }

  50% { transform: rotate(225deg) }

  100% { transform: rotate(180deg) }
}
@keyframes ldio-acn7vapfu5-3 {

  0% { transform: translate(117.8px,0); opacity: 0 }

  20% { opacity: 1 }

  100% { transform: translate(43.4px,0); opacity: 1 }
}

.ldio-acn7vapfu5 > div:nth-child(2) {
  transform: translate(-15px,0);
}

.ldio-acn7vapfu5 > div:nth-child(2) div {
  position: absolute;
  top: 24.8px;
  left: 24.8px;
  width: 74.4px;
  height: 37.2px;
  border-radius: 74.4px 74.4px 0 0;
  background: #93dbe9;
  animation: ldio-acn7vapfu5-1 .819672131147541s linear infinite;
  transform-origin: 37.2px 37.2px
}

.ldio-acn7vapfu5 > div:nth-child(2) div:nth-child(2) {
  animation: ldio-acn7vapfu5-2 .819672131147541s linear infinite
}

.ldio-acn7vapfu5 > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}

.ldio-acn7vapfu5 > div:nth-child(1) {
  display: block;
}

.ldio-acn7vapfu5 > div:nth-child(1) div {
  position: absolute;
  top: 57.04px;
  left: -4.96px;
  width: 9.92px;
  height: 9.92px;
  border-radius: 50%;
  background: #689cc5;
  animation: ldio-acn7vapfu5-3 .819672131147541s linear infinite
}

.ldio-acn7vapfu5 > div:nth-child(1) div:nth-child(1) { animation-delay: -.8174s }

.ldio-acn7vapfu5 > div:nth-child(1) div:nth-child(2) { animation-delay: -.4026s }

.ldio-acn7vapfu5 > div:nth-child(1) div:nth-child(3) { animation-delay: 0s }

.loadingio-spinner-bean-eater-0lnlvb57159i {
  width: 124px;
  height: 124px;
  display: inline-block;
  overflow: hidden;
  // background: rgba(NaN, NaN, NaN, 0);
}

.ldio-acn7vapfu5 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}

.ldio-acn7vapfu5 div { box-sizing: content-box; }

/* generated by https://loading.io/ */
</style>
